# Feature Table Inspection

モデル構築に使用する施設のデータと、モデルの評価（external evaluation）に使う施設のデータを分割して保存する

## Set Config

In [1]:
# ライブラリのインポート
import os
import numpy as np
import polars as pl
from sklearn.model_selection import train_test_split
from sklearn.metrics import roc_auc_score
import seaborn as sns

In [2]:
# フォルダ設定
data_dir = '../data/'
output_dir = '../output/'

# date
date = '20260202_emergency'

# 特徴量tableのファイル名
feature_table = f'{date}_features.csv'

In [3]:
# 保存するファイル名の指定
df_development_file_name = f'{date}_df_development_raw.csv'
# df_evaluation_file_name = f'{date}_df_evaluation_raw.csv'

## Load data

In [4]:
df = pl.read_csv(os.path.join(data_dir + feature_table))

In [5]:
# record数と症例数を確認
print('Number of records:', len(df))
print('Number of icu_stay_id:', len(df['icu_stay_id'].unique()))
print('Average number of records per icu_stay_id:', len(df) / len(df['icu_stay_id'].unique()))

Number of records: 4899756
Number of icu_stay_id: 41300
Average number of records per icu_stay_id: 118.6381598062954

In [6]:

# SEED = 42  # 再現性のため
# 1) ICU滞在IDのユニーク集合を作る
# ids = df.select("icu_stay_id").unique()
# n_ids = ids.height

# 2) 1/100だけサンプル（最低1件は確保）
# n_sample = max(1, n_ids // 50)
# ids_sampled = ids.sample(n=n_sample, shuffle=True, seed=SEED)

# 3) 選ばれたIDの症例のみ残す（semi join）
# df_sampled = df.join(ids_sampled, on="icu_stay_id", how="semi")

# record数と症例数を確認
# print('Number of records:', len(df_sampled))
# print('Number of icu_stay_id:', len(df_sampled['icu_stay_id'].unique()))
# print('Average number of records per icu_stay_id:', len(df_sampled) / len(df_sampled['icu_stay_id'].unique()))

# Inspect Feature Table

In [7]:
def describe_df(df: pl.DataFrame, start: int, end: int) -> pl.DataFrame:
    return df[:, start:end].describe()

In [8]:
df.head()

shape: (5, 221)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ icu_stay_ ┆ time_wind ┆ start_tim ┆ end_time  ┆ … ┆ transfusi ┆ transfusi ┆ transfusi ┆ transfus │
│ id        ┆ ow_index  ┆ e         ┆ ---       ┆   ┆ on_rbc    ┆ on_platel ┆ on_plasma ┆ ion_albu │
│ ---       ┆ ---       ┆ ---       ┆ str       ┆   ┆ ---       ┆ et        ┆ ---       ┆ min      │
│ i64       ┆ i64       ┆ str       ┆           ┆   ┆ f64       ┆ ---       ┆ f64       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆ f64       ┆           ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 102132585 ┆ 21        ┆ 2200-01-0 ┆ 2200-01-0 ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0      │
│ 217715404 ┆           ┆ 2         ┆ 2         ┆   ┆           ┆           ┆           ┆          │
│ 8         ┆           ┆ 09:00:00  ┆ 10:00:00  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ UTC       ┆ UTC       ┆   ┆           ┆           ┆           ┆          │
│ 102132585 ┆ 22        ┆ 2200-01-0 ┆ 2200-01-0 ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0      │
│ 217715404 ┆           ┆ 2         ┆ 2         ┆   ┆           ┆           ┆           ┆          │
│ 8         ┆           ┆ 10:00:00  ┆ 11:00:00  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ UTC       ┆ UTC       ┆   ┆           ┆           ┆           ┆          │
│ 102132585 ┆ 23        ┆ 2200-01-0 ┆ 2200-01-0 ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0      │
│ 217715404 ┆           ┆ 2         ┆ 2         ┆   ┆           ┆           ┆           ┆          │
│ 8         ┆           ┆ 11:00:00  ┆ 12:00:00  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ UTC       ┆ UTC       ┆   ┆           ┆           ┆           ┆          │
│ 102132585 ┆ 24        ┆ 2200-01-0 ┆ 2200-01-0 ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0      │
│ 217715404 ┆           ┆ 2         ┆ 2         ┆   ┆           ┆           ┆           ┆          │
│ 8         ┆           ┆ 12:00:00  ┆ 13:00:00  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ UTC       ┆ UTC       ┆   ┆           ┆           ┆           ┆          │
│ 102132585 ┆ 25        ┆ 2200-01-0 ┆ 2200-01-0 ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0      │
│ 217715404 ┆           ┆ 2         ┆ 2         ┆   ┆           ┆           ┆           ┆          │
│ 8         ┆           ┆ 13:00:00  ┆ 14:00:00  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ UTC       ┆ UTC       ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [9]:
df["label_delirium_indication"].describe()

shape: (9, 2)
┌────────────┬────────────┐
│ statistic  ┆ value      │
│ ---        ┆ ---        │
│ str        ┆ f64        │
╞════════════╪════════════╡
│ count      ┆ 4.899756e6 │
│ null_count ┆ 0.0        │
│ mean       ┆ 0.190427   │
│ std        ┆ 0.392638   │
│ min        ┆ 0.0        │
│ 25%        ┆ 0.0        │
│ 50%        ┆ 0.0        │
│ 75%        ┆ 0.0        │
│ max        ┆ 1.0        │
└────────────┴────────────┘

In [10]:
describe_df(df, 0, 10)

shape: (9, 11)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ statistic ┆ icu_stay_ ┆ time_wind ┆ start_tim ┆ … ┆ hospital_ ┆ icu_admit ┆ female    ┆ age      │
│ ---       ┆ id        ┆ ow_index  ┆ e         ┆   ┆ id        ┆ _time     ┆ ---       ┆ ---      │
│ str       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ f64       ┆ f64      │
│           ┆ f64       ┆ f64       ┆ str       ┆   ┆ f64       ┆ f64       ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ count     ┆ 4.899756e ┆ 4.899756e ┆ 4899756   ┆ … ┆ 4.899756e ┆ 4.899756e ┆ 4.899756e ┆ 4.899756 │
│           ┆ 6         ┆ 6         ┆           ┆   ┆ 6         ┆ 6         ┆ 6         ┆ e6       │
│ null_coun ┆ 0.0       ┆ 0.0       ┆ 0         ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0      │
│ t         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ mean      ┆ 5.7932e17 ┆ 227.44015 ┆ null      ┆ … ┆ 4.449725  ┆ 13.524164 ┆ 0.367817  ┆ 65.51275 │
│           ┆           ┆ 7         ┆           ┆   ┆           ┆           ┆           ┆ 9        │
│ std       ┆ 3.3216e17 ┆ 387.25688 ┆ null      ┆ … ┆ 3.526787  ┆ 5.827828  ┆ 0.482211  ┆ 17.28858 │
│           ┆           ┆ 6         ┆           ┆   ┆           ┆           ┆           ┆ 5        │
│ min       ┆ 2.8023e13 ┆ 0.0       ┆ 2200-01-0 ┆ … ┆ 1.0       ┆ 0.0       ┆ 0.0       ┆ 15.0     │
│           ┆           ┆           ┆ 1         ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 00:00:00  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ UTC       ┆   ┆           ┆           ┆           ┆          │
│ 25%       ┆ 2.9493e17 ┆ 38.0      ┆ null      ┆ … ┆ 1.0       ┆ 10.0      ┆ 0.0       ┆ 55.0     │
│ 50%       ┆ 5.8050e17 ┆ 109.0     ┆ null      ┆ … ┆ 3.0       ┆ 14.0      ┆ 0.0       ┆ 70.0     │
│ 75%       ┆ 8.6824e17 ┆ 264.0     ┆ null      ┆ … ┆ 7.0       ┆ 18.0      ┆ 1.0       ┆ 78.0     │
│ max       ┆ 1.1528e18 ┆ 8209.0    ┆ 2211-11-0 ┆ … ┆ 11.0      ┆ 23.0      ┆ 1.0       ┆ 99.0     │
│           ┆           ┆           ┆ 6         ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 09:00:00  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ UTC       ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [11]:
describe_df(df, 10, 20)

shape: (9, 11)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ statistic ┆ icu_admis ┆ diagnosis ┆ covid19   ┆ … ┆ anaphylax ┆ burn      ┆ temperatu ┆ hanging_ │
│ ---       ┆ sion_type ┆ _category ┆ ---       ┆   ┆ is        ┆ ---       ┆ re_disord ┆ asphyxia │
│ str       ┆ ---       ┆ ---       ┆ f64       ┆   ┆ ---       ┆ f64       ┆ er        ┆ tion     │
│           ┆ str       ┆ str       ┆           ┆   ┆ f64       ┆           ┆ ---       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ count     ┆ 4899756   ┆ 4899756   ┆ 4.899756e ┆ … ┆ 4.899756e ┆ 4.899756e ┆ 4.899756e ┆ 4.899756 │
│           ┆           ┆           ┆ 6         ┆   ┆ 6         ┆ 6         ┆ 6         ┆ e6       │
│ null_coun ┆ 0         ┆ 0         ┆ 0.0       ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0      │
│ t         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ mean      ┆ null      ┆ null      ┆ 0.091321  ┆ … ┆ 0.000665  ┆ 0.013327  ┆ 0.011987  ┆ 0.001881 │
│ std       ┆ null      ┆ null      ┆ 0.288065  ┆ … ┆ 0.025774  ┆ 0.114672  ┆ 0.108827  ┆ 0.043333 │
│ min       ┆ emergency ┆ anaphylax ┆ 0.0       ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0      │
│           ┆           ┆ is        ┆           ┆   ┆           ┆           ┆           ┆          │
│ 25%       ┆ null      ┆ null      ┆ 0.0       ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0      │
│ 50%       ┆ null      ┆ null      ┆ 0.0       ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0      │
│ 75%       ┆ null      ┆ null      ┆ 0.0       ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0      │
│ max       ┆ emergency ┆ trauma    ┆ 1.0       ┆ … ┆ 1.0       ┆ 1.0       ┆ 1.0       ┆ 1.0      │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [12]:
describe_df(df, 20, 30)

shape: (9, 11)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ statistic ┆ trauma    ┆ infection ┆ neoplasms ┆ … ┆ neurologi ┆ genitouri ┆ electroly ┆ musculos │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ cal       ┆ nary      ┆ te_metabo ┆ keletal  │
│ str       ┆ f64       ┆ f64       ┆ f64       ┆   ┆ ---       ┆ ---       ┆ lic_disor ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆ f64       ┆ f64       ┆ der…      ┆ f64      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ ---       ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ f64       ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ count     ┆ 4.899756e ┆ 4.899756e ┆ 4.899756e ┆ … ┆ 4.899756e ┆ 4.899756e ┆ 4.899756e ┆ 4.899756 │
│           ┆ 6         ┆ 6         ┆ 6         ┆   ┆ 6         ┆ 6         ┆ 6         ┆ e6       │
│ null_coun ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0      │
│ t         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ mean      ┆ 0.134807  ┆ 0.107013  ┆ 0.045766  ┆ … ┆ 0.025841  ┆ 0.018733  ┆ 0.038843  ┆ 0.021927 │
│ std       ┆ 0.341517  ┆ 0.309129  ┆ 0.208978  ┆ … ┆ 0.158661  ┆ 0.135582  ┆ 0.193221  ┆ 0.146446 │
│ min       ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0      │
│ 25%       ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0      │
│ 50%       ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0      │
│ 75%       ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0      │
│ max       ┆ 1.0       ┆ 1.0       ┆ 1.0       ┆ … ┆ 1.0       ┆ 1.0       ┆ 1.0       ┆ 1.0      │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [13]:
describe_df(df, 30, 40)

shape: (9, 11)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ statistic ┆ psychiatr ┆ congenita ┆ undefined ┆ … ┆ charlson_ ┆ myocardia ┆ congestiv ┆ peripher │
│ ---       ┆ ic        ┆ l         ┆ ---       ┆   ┆ comorbidi ┆ l_infarct ┆ e_heart_f ┆ al_arter │
│ str       ┆ ---       ┆ ---       ┆ f64       ┆   ┆ ty_index  ┆ ---       ┆ ailure    ┆ ial_dise │
│           ┆ f64       ┆ f64       ┆           ┆   ┆ ---       ┆ f64       ┆ ---       ┆ ase      │
│           ┆           ┆           ┆           ┆   ┆ f64       ┆           ┆ f64       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ count     ┆ 4.899756e ┆ 4.899756e ┆ 4.899756e ┆ … ┆ 4.899756e ┆ 4.899756e ┆ 4.899756e ┆ 4.899756 │
│           ┆ 6         ┆ 6         ┆ 6         ┆   ┆ 6         ┆ 6         ┆ 6         ┆ e6       │
│ null_coun ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0      │
│ t         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ mean      ┆ 0.008715  ┆ 0.002619  ┆ 0.018575  ┆ … ┆ 3.217867  ┆ 0.045141  ┆ 0.107883  ┆ 0.065867 │
│ std       ┆ 0.092948  ┆ 0.051106  ┆ 0.13502   ┆ … ┆ 2.728794  ┆ 0.207614  ┆ 0.310233  ┆ 0.24805  │
│ min       ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0      │
│ 25%       ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ … ┆ 2.0       ┆ 0.0       ┆ 0.0       ┆ 0.0      │
│ 50%       ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ … ┆ 3.0       ┆ 0.0       ┆ 0.0       ┆ 0.0      │
│ 75%       ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ … ┆ 4.0       ┆ 0.0       ┆ 0.0       ┆ 0.0      │
│ max       ┆ 1.0       ┆ 1.0       ┆ 1.0       ┆ … ┆ 25.0      ┆ 1.0       ┆ 1.0       ┆ 1.0      │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [14]:
describe_df(df, 40, 50)

shape: (9, 11)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ statistic ┆ cerebrova ┆ dementia  ┆ chronic_p ┆ … ┆ diabetes_ ┆ diabetes_ ┆ paraplegi ┆ renal_di │
│ ---       ┆ scular_di ┆ ---       ┆ ulmonary_ ┆   ┆ without_c ┆ with_cc   ┆ a         ┆ sease    │
│ str       ┆ sease     ┆ f64       ┆ disease   ┆   ┆ c         ┆ ---       ┆ ---       ┆ ---      │
│           ┆ ---       ┆           ┆ ---       ┆   ┆ ---       ┆ f64       ┆ f64       ┆ f64      │
│           ┆ f64       ┆           ┆ f64       ┆   ┆ f64       ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ count     ┆ 4.899756e ┆ 4.899756e ┆ 4.899756e ┆ … ┆ 4.899756e ┆ 4.899756e ┆ 4.899756e ┆ 4.899756 │
│           ┆ 6         ┆ 6         ┆ 6         ┆   ┆ 6         ┆ 6         ┆ 6         ┆ e6       │
│ null_coun ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0      │
│ t         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ mean      ┆ 0.101155  ┆ 0.009834  ┆ 0.036346  ┆ … ┆ 0.032106  ┆ 0.019691  ┆ 0.006175  ┆ 0.049488 │
│ std       ┆ 0.301534  ┆ 0.098677  ┆ 0.187149  ┆ … ┆ 0.176281  ┆ 0.138935  ┆ 0.078339  ┆ 0.216884 │
│ min       ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0      │
│ 25%       ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0      │
│ 50%       ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0      │
│ 75%       ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0      │
│ max       ┆ 1.0       ┆ 1.0       ┆ 1.0       ┆ … ┆ 1.0       ┆ 1.0       ┆ 1.0       ┆ 1.0      │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [15]:
describe_df(df, 50, 60)

shape: (9, 11)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ statistic ┆ malignant ┆ severe_li ┆ metastati ┆ … ┆ fio2_orde ┆ fio2_orde ┆ delta_fio ┆ delta_fi │
│ ---       ┆ _cancer   ┆ ver_disea ┆ c_solid_t ┆   ┆ red       ┆ red_is_cu ┆ 2_ordered ┆ o2_order │
│ str       ┆ ---       ┆ se        ┆ umor      ┆   ┆ ---       ┆ rrent_val ┆ _lag1     ┆ ed_lag6  │
│           ┆ f64       ┆ ---       ┆ ---       ┆   ┆ str       ┆ ue        ┆ ---       ┆ ---      │
│           ┆           ┆ f64       ┆ f64       ┆   ┆           ┆ ---       ┆ str       ┆ str      │
│           ┆           ┆           ┆           ┆   ┆           ┆ f64       ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ count     ┆ 4.899756e ┆ 4.899756e ┆ 4.899756e ┆ … ┆ 3173278   ┆ 4.899756e ┆ 2156921   ┆ 2042117  │
│           ┆ 6         ┆ 6         ┆ 6         ┆   ┆           ┆ 6         ┆           ┆          │
│ null_coun ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ … ┆ 1726478   ┆ 0.0       ┆ 2742835   ┆ 2857639  │
│ t         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ mean      ┆ 0.094231  ┆ 0.010084  ┆ 0.021831  ┆ … ┆ null      ┆ 0.445576  ┆ null      ┆ null     │
│ std       ┆ 0.29215   ┆ 0.099912  ┆ 0.146132  ┆ … ┆ null      ┆ 0.497029  ┆ null      ┆ null     │
│ min       ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ … ┆ 100.0     ┆ 0.0       ┆ -1.0      ┆ -1.0     │
│ 25%       ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ … ┆ null      ┆ 0.0       ┆ null      ┆ null     │
│ 50%       ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ … ┆ null      ┆ 0.0       ┆ null      ┆ null     │
│ 75%       ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ … ┆ null      ┆ 1.0       ┆ null      ┆ null     │
│ max       ┆ 1.0       ┆ 1.0       ┆ 1.0       ┆ … ┆ 99.0      ┆ 1.0       ┆ 9.9999999 ┆ 9.999999 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 99999993  ┆ 99999999 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 3        │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [16]:
describe_df(df, 60, 70)

shape: (9, 11)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ statistic ┆ delta_fio ┆ peep_orde ┆ peep_orde ┆ … ┆ inspirato ┆ time_sinc ┆ mv_durati ┆ ph       │
│ ---       ┆ 2_ordered ┆ red       ┆ red_is_cu ┆   ┆ ry_pressu ┆ e_last_co ┆ on        ┆ ---      │
│ str       ┆ _lag12    ┆ ---       ┆ rrent_val ┆   ┆ re        ┆ ntrol_ven ┆ ---       ┆ f64      │
│           ┆ ---       ┆ str       ┆ ue        ┆   ┆ ---       ┆ til…      ┆ f64       ┆          │
│           ┆ str       ┆           ┆ ---       ┆   ┆ str       ┆ ---       ┆           ┆          │
│           ┆           ┆           ┆ f64       ┆   ┆           ┆ f64       ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ count     ┆ 1931919   ┆ 3164739   ┆ 4.899756e ┆ … ┆ 2835259   ┆ 3.565127e ┆ 4.899756e ┆ 3.452868 │
│           ┆           ┆           ┆ 6         ┆   ┆           ┆ 6         ┆ 6         ┆ e6       │
│ null_coun ┆ 2967837   ┆ 1735017   ┆ 0.0       ┆ … ┆ 2064497   ┆ 1.334629e ┆ 0.0       ┆ 1.446888 │
│ t         ┆           ┆           ┆           ┆   ┆           ┆ 6         ┆           ┆ e6       │
│ mean      ┆ null      ┆ null      ┆ 0.445483  ┆ … ┆ null      ┆ 51.53172  ┆ 75.632598 ┆ 7.422221 │
│ std       ┆ null      ┆ null      ┆ 0.497019  ┆ … ┆ null      ┆ 167.50729 ┆ 213.90595 ┆ 0.072504 │
│           ┆           ┆           ┆           ┆   ┆           ┆ 5         ┆ 5         ┆          │
│ min       ┆ -1.0      ┆ -2.0      ┆ 0.0       ┆ … ┆ -1.0      ┆ 0.0       ┆ 0.0       ┆ 6.343    │
│ 25%       ┆ null      ┆ null      ┆ 0.0       ┆ … ┆ null      ┆ 0.0       ┆ 0.0       ┆ 7.39     │
│ 50%       ┆ null      ┆ null      ┆ 0.0       ┆ … ┆ null      ┆ 0.0       ┆ 0.0       ┆ 7.431    │
│ 75%       ┆ null      ┆ null      ┆ 1.0       ┆ … ┆ null      ┆ 23.0      ┆ 73.0      ┆ 7.467    │
│ max       ┆ 9.9999999 ┆ NaN       ┆ 1.0       ┆ … ┆ NaN       ┆ 3815.0    ┆ 6590.0    ┆ 7.984    │
│           ┆ 99999993  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [17]:
describe_df(df, 70, 80)

shape: (9, 11)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ statistic ┆ pao2      ┆ pvo2      ┆ paco2     ┆ … ┆ gcs_e     ┆ gcs_v     ┆ gcs_m     ┆ body_wei │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ght      │
│ str       ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ count     ┆ 3.286853e ┆ 337890.0  ┆ 3.290348e ┆ … ┆ 4.80733e6 ┆ 4.807264e ┆ 4.807189e ┆ 4.206564 │
│           ┆ 6         ┆           ┆ 6         ┆   ┆           ┆ 6         ┆ 6         ┆ e6       │
│ null_coun ┆ 1.612903e ┆ 4.561866e ┆ 1.609408e ┆ … ┆ 92426.0   ┆ 92492.0   ┆ 92567.0   ┆ 693192.0 │
│ t         ┆ 6         ┆ 6         ┆ 6         ┆   ┆           ┆           ┆           ┆          │
│ mean      ┆ 103.69034 ┆ 46.254681 ┆ 38.840878 ┆ … ┆ 2.923816  ┆ 2.774542  ┆ 4.633805  ┆ 60.58089 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 1        │
│ std       ┆ 47.083938 ┆ 23.550839 ┆ 8.837953  ┆ … ┆ 1.233801  ┆ 1.889652  ┆ 1.943084  ┆ 15.92859 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 7        │
│ min       ┆ 8.0       ┆ 2.7       ┆ 5.0       ┆ … ┆ 1.0       ┆ 1.0       ┆ 1.0       ┆ 1.0      │
│ 25%       ┆ 77.3      ┆ 33.2      ┆ 33.7      ┆ … ┆ 2.0       ┆ 1.0       ┆ 4.0       ┆ 49.7     │
│ 50%       ┆ 92.6      ┆ 41.8      ┆ 37.8      ┆ … ┆ 3.0       ┆ 1.0       ┆ 6.0       ┆ 58.9     │
│ 75%       ┆ 117.0     ┆ 53.4      ┆ 42.4      ┆ … ┆ 4.0       ┆ 5.0       ┆ 6.0       ┆ 69.4     │
│ max       ┆ 1592.0    ┆ 560.0     ┆ 754.0     ┆ … ┆ 4.0       ┆ 5.0       ┆ 6.0       ┆ 200.0    │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [18]:
describe_df(df, 80, 90)

shape: (9, 11)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ statistic ┆ bt50      ┆ hr10      ┆ hr50      ┆ … ┆ delta_hr1 ┆ delta_hr1 ┆ delta_hr5 ┆ delta_hr │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ 0_lag6    ┆ 0_lag12   ┆ 0_lag1    ┆ 50_lag6  │
│ str       ┆ f64       ┆ f64       ┆ f64       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ count     ┆ 4.531271e ┆ 4.7702e6  ┆ 4.7702e6  ┆ … ┆ 4.441742e ┆ 4.221078e ┆ 4.65112e6 ┆ 4.441742 │
│           ┆ 6         ┆           ┆           ┆   ┆ 6         ┆ 6         ┆           ┆ e6       │
│ null_coun ┆ 368485.0  ┆ 129556.0  ┆ 129556.0  ┆ … ┆ 458014.0  ┆ 678678.0  ┆ 248636.0  ┆ 458014.0 │
│ t         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ mean      ┆ 37.152272 ┆ 80.502817 ┆ 84.494434 ┆ … ┆ -0.332805 ┆ -0.503413 ┆ -0.09861  ┆ -0.34116 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 7        │
│ std       ┆ 1.016618  ┆ 18.557457 ┆ 19.069825 ┆ … ┆ 10.973488 ┆ 13.020507 ┆ 6.174778  ┆ 11.39768 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 3        │
│ min       ┆ 10.0      ┆ 0.0       ┆ 0.0       ┆ … ┆ -183.0    ┆ -218.0    ┆ -205.5    ┆ -203.0   │
│ 25%       ┆ 36.6      ┆ 67.0      ┆ 71.0      ┆ … ┆ -5.0      ┆ -7.0      ┆ -2.0      ┆ -5.5     │
│ 50%       ┆ 37.1      ┆ 79.0      ┆ 83.0      ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0      │
│ 75%       ┆ 37.7      ┆ 92.0      ┆ 96.0      ┆ … ┆ 4.9       ┆ 6.0       ┆ 2.0       ┆ 5.0      │
│ max       ┆ 45.0      ┆ 267.0     ┆ 269.0     ┆ … ┆ 182.0     ┆ 184.0     ┆ 203.0     ┆ 203.0    │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [19]:
describe_df(df, 90, 100)

shape: (9, 11)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ statistic ┆ delta_hr5 ┆ delta_hr9 ┆ delta_hr9 ┆ … ┆ delta_hr_ ┆ rr10      ┆ rr50      ┆ rr90     │
│ ---       ┆ 0_lag12   ┆ 0_lag1    ┆ 0_lag6    ┆   ┆ sd_lag12  ┆ ---       ┆ ---       ┆ ---      │
│ str       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ f64       ┆ f64       ┆ f64      │
│           ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ count     ┆ 4.221078e ┆ 4.65112e6 ┆ 4.441742e ┆ … ┆ 4.181261e ┆ 4.685357e ┆ 4.685357e ┆ 4.685357 │
│           ┆ 6         ┆           ┆ 6         ┆   ┆ 6         ┆ 6         ┆ 6         ┆ e6       │
│ null_coun ┆ 678678.0  ┆ 248636.0  ┆ 458014.0  ┆ … ┆ 718495.0  ┆ 214399.0  ┆ 214399.0  ┆ 214399.0 │
│ t         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ mean      ┆ -0.495259 ┆ -0.114302 ┆ -0.342166 ┆ … ┆ 0.014165  ┆ 15.180693 ┆ 17.797005 ┆ 21.12070 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 8        │
│ std       ┆ 13.58306  ┆ 7.737659  ┆ 12.996803 ┆ … ┆ 3.993541  ┆ 6.396895  ┆ 7.195327  ┆ 8.502654 │
│ min       ┆ -203.0    ┆ -212.4    ┆ -259.4    ┆ … ┆ -130.8429 ┆ 0.0       ┆ 0.0       ┆ 0.0      │
│           ┆           ┆           ┆           ┆   ┆ 56        ┆           ┆           ┆          │
│ 25%       ┆ -7.0      ┆ -3.0      ┆ -6.0      ┆ … ┆ -1.245678 ┆ 12.0      ┆ 15.0      ┆ 17.0     │
│ 50%       ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ … ┆ 0.027592  ┆ 15.0      ┆ 18.0      ┆ 21.0     │
│ 75%       ┆ 6.0       ┆ 2.9       ┆ 5.1       ┆ … ┆ 1.314091  ┆ 18.9      ┆ 22.0      ┆ 26.0     │
│ max       ┆ 203.0     ┆ 232.9     ┆ 259.4     ┆ … ┆ 107.68778 ┆ 100.0     ┆ 100.0     ┆ 100.0    │
│           ┆           ┆           ┆           ┆   ┆ 9         ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [20]:
describe_df(df, 100, 110)

shape: (9, 11)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ statistic ┆ rr_sd     ┆ delta_rr1 ┆ delta_rr1 ┆ … ┆ delta_rr5 ┆ delta_rr9 ┆ delta_rr9 ┆ delta_rr │
│ ---       ┆ ---       ┆ 0_lag1    ┆ 0_lag6    ┆   ┆ 0_lag12   ┆ 0_lag1    ┆ 0_lag6    ┆ 90_lag12 │
│ str       ┆ f64       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│           ┆           ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ count     ┆ 4.636135e ┆ 4.564616e ┆ 4.350629e ┆ … ┆ 4.128962e ┆ 4.564616e ┆ 4.350629e ┆ 4.128962 │
│           ┆ 6         ┆ 6         ┆ 6         ┆   ┆ 6         ┆ 6         ┆ 6         ┆ e6       │
│ null_coun ┆ 263621.0  ┆ 335140.0  ┆ 549127.0  ┆ … ┆ 770794.0  ┆ 335140.0  ┆ 549127.0  ┆ 770794.0 │
│ t         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ mean      ┆ 2.762255  ┆ 0.009404  ┆ 0.022417  ┆ … ┆ 0.070953  ┆ -0.009951 ┆ 0.044705  ┆ 0.109257 │
│ std       ┆ 2.062952  ┆ 2.634907  ┆ 3.881038  ┆ … ┆ 4.81619   ┆ 3.619172  ┆ 5.325896  ┆ 6.080435 │
│ min       ┆ 0.0       ┆ -81.0     ┆ -80.0     ┆ … ┆ -82.5     ┆ -91.5     ┆ -100.0    ┆ -96.6    │
│ 25%       ┆ 1.416072  ┆ -1.0      ┆ -1.0      ┆ … ┆ -2.0      ┆ -1.0      ┆ -2.0      ┆ -2.1     │
│ 50%       ┆ 2.467873  ┆ 0.0       ┆ 0.0       ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0      │
│ 75%       ┆ 3.664587  ┆ 1.0       ┆ 1.0       ┆ … ┆ 2.0       ┆ 1.0       ┆ 2.0       ┆ 2.9      │
│ max       ┆ 51.618795 ┆ 80.0      ┆ 80.1      ┆ … ┆ 86.0      ┆ 90.5      ┆ 99.4      ┆ 99.4     │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [21]:
describe_df(df, 110, 120)

shape: (9, 11)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ statistic ┆ delta_rr_ ┆ delta_rr_ ┆ delta_rr_ ┆ … ┆ sbp_sd    ┆ delta_sbp ┆ delta_sbp ┆ delta_sb │
│ ---       ┆ sd_lag1   ┆ sd_lag6   ┆ sd_lag12  ┆   ┆ ---       ┆ 10_lag1   ┆ 10_lag6   ┆ p10_lag1 │
│ str       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ f64       ┆ ---       ┆ ---       ┆ 2        │
│           ┆ f64       ┆ f64       ┆ f64       ┆   ┆           ┆ f64       ┆ f64       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ count     ┆ 4.528658e ┆ 4.31285e6 ┆ 4.090695e ┆ … ┆ 3.564536e ┆ 3.401254e ┆ 3.262747e ┆ 3.087116 │
│           ┆ 6         ┆           ┆ 6         ┆   ┆ 6         ┆ 6         ┆ 6         ┆ e6       │
│ null_coun ┆ 371098.0  ┆ 586906.0  ┆ 809061.0  ┆ … ┆ 1.33522e6 ┆ 1.498502e ┆ 1.637009e ┆ 1.81264e │
│ t         ┆           ┆           ┆           ┆   ┆           ┆ 6         ┆ 6         ┆ 6        │
│ mean      ┆ -0.006999 ┆ 0.007491  ┆ 0.027899  ┆ … ┆ 9.077244  ┆ -0.067508 ┆ 0.201889  ┆ 0.47857  │
│ std       ┆ 1.590117  ┆ 1.917535  ┆ 2.043674  ┆ … ┆ 7.619924  ┆ 14.131445 ┆ 21.016345 ┆ 23.33893 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 6        │
│ min       ┆ -50.45613 ┆ -50.71090 ┆ -49.35916 ┆ … ┆ 0.0       ┆ -285.3    ┆ -284.1    ┆ -230.6   │
│           ┆ 5         ┆ 8         ┆ 4         ┆   ┆           ┆           ┆           ┆          │
│ 25%       ┆ -0.644723 ┆ -0.801112 ┆ -0.865373 ┆ … ┆ 4.441586  ┆ -5.8      ┆ -10.9     ┆ -12.3    │
│ 50%       ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ … ┆ 7.071068  ┆ 0.0       ┆ 0.2       ┆ 0.7      │
│ 75%       ┆ 0.639655  ┆ 0.836636  ┆ 0.941622  ┆ … ┆ 11.294917 ┆ 5.9       ┆ 11.2      ┆ 13.8     │
│ max       ┆ 50.565964 ┆ 50.565964 ┆ 50.565964 ┆ … ┆ 207.88939 ┆ 274.0     ┆ 246.0     ┆ 244.4    │
│           ┆           ┆           ┆           ┆   ┆ 4         ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [22]:
describe_df(df, 120, 130)

shape: (9, 11)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ statistic ┆ delta_sbp ┆ delta_sbp ┆ delta_sbp ┆ … ┆ delta_sbp ┆ delta_sbp ┆ delta_sbp ┆ mbp10    │
│ ---       ┆ 50_lag1   ┆ 50_lag6   ┆ 50_lag12  ┆   ┆ _sd_lag1  ┆ _sd_lag6  ┆ _sd_lag12 ┆ ---      │
│ str       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ f64      │
│           ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ count     ┆ 3.401254e ┆ 3.262747e ┆ 3.087116e ┆ … ┆ 3.20425e6 ┆ 3.018295e ┆ 2.835083e ┆ 4.514439 │
│           ┆ 6         ┆ 6         ┆ 6         ┆   ┆           ┆ 6         ┆ 6         ┆ e6       │
│ null_coun ┆ 1.498502e ┆ 1.637009e ┆ 1.81264e6 ┆ … ┆ 1.695506e ┆ 1.881461e ┆ 2.064673e ┆ 385317.0 │
│ t         ┆ 6         ┆ 6         ┆           ┆   ┆ 6         ┆ 6         ┆ 6         ┆          │
│ mean      ┆ -0.125179 ┆ 0.052656  ┆ 0.336639  ┆ … ┆ -0.054925 ┆ -0.094439 ┆ -0.057535 ┆ 77.98467 │
│ std       ┆ 13.255427 ┆ 20.595036 ┆ 23.060634 ┆ … ┆ 7.193381  ┆ 8.060263  ┆ 8.3309    ┆ 17.36263 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 2        │
│ min       ┆ -278.0    ┆ -262.0    ┆ -248.5    ┆ … ┆ -203.2339 ┆ -198.1911 ┆ -203.6081 ┆ 0.0      │
│           ┆           ┆           ┆           ┆   ┆ 45        ┆ 85        ┆ 16        ┆          │
│ 25%       ┆ -5.0      ┆ -10.5     ┆ -12.0     ┆ … ┆ -2.712104 ┆ -3.12511  ┆ -3.313569 ┆ 66.0     │
│ 50%       ┆ 0.0       ┆ 0.5       ┆ 0.5       ┆ … ┆ -0.032509 ┆ -0.012324 ┆ 0.027893  ┆ 77.0     │
│ 75%       ┆ 5.5       ┆ 11.0      ┆ 13.0      ┆ … ┆ 2.620485  ┆ 3.061073  ┆ 3.324042  ┆ 88.7     │
│ max       ┆ 267.0     ┆ 235.0     ┆ 253.0     ┆ … ┆ 200.03867 ┆ 203.82688 ┆ 185.42525 ┆ 300.0    │
│           ┆           ┆           ┆           ┆   ┆ 7         ┆ 8         ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [23]:
describe_df(df, 130, 140)

shape: (9, 11)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ statistic ┆ mbp50     ┆ mbp90     ┆ mbp_sd    ┆ … ┆ delta_mbp ┆ delta_mbp ┆ delta_mbp ┆ delta_mb │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ 50_lag1   ┆ 50_lag6   ┆ 50_lag12  ┆ p90_lag1 │
│ str       ┆ f64       ┆ f64       ┆ f64       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ count     ┆ 4.514439e ┆ 4.514439e ┆ 3.565571e ┆ … ┆ 3.401334e ┆ 3.262765e ┆ 3.087131e ┆ 3.401334 │
│           ┆ 6         ┆ 6         ┆ 6         ┆   ┆ 6         ┆ 6         ┆ 6         ┆ e6       │
│ null_coun ┆ 385317.0  ┆ 385317.0  ┆ 1.334185e ┆ … ┆ 1.498422e ┆ 1.636991e ┆ 1.812625e ┆ 1.498422 │
│ t         ┆           ┆           ┆ 6         ┆   ┆ 6         ┆ 6         ┆ 6         ┆ e6       │
│ mean      ┆ 82.302116 ┆ 87.924327 ┆ 6.828234  ┆ … ┆ -0.087008 ┆ -0.000012 ┆ 0.142925  ┆ -0.12745 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 1        │
│ std       ┆ 17.478416 ┆ 19.87773  ┆ 7.520599  ┆ … ┆ 9.492047  ┆ 13.970012 ┆ 15.540202 ┆ 13.54094 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 2        │
│ min       ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ … ┆ -290.0    ┆ -268.0    ┆ -244.3333 ┆ -292.7   │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 33        ┆          │
│ 25%       ┆ 71.0      ┆ 75.0      ┆ 2.910918  ┆ … ┆ -3.0      ┆ -7.0      ┆ -8.0      ┆ -4.0     │
│ 50%       ┆ 81.0      ┆ 86.0      ┆ 4.706338  ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0      │
│ 75%       ┆ 93.0      ┆ 98.2      ┆ 7.815872  ┆ … ┆ 3.5       ┆ 7.0       ┆ 8.5       ┆ 4.0      │
│ max       ┆ 300.0     ┆ 300.0     ┆ 200.81832 ┆ … ┆ 275.0     ┆ 240.0     ┆ 256.5     ┆ 275.0    │
│           ┆           ┆           ┆ 6         ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [24]:
describe_df(df, 140, 150)

shape: (9, 11)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ statistic ┆ delta_mbp ┆ delta_mbp ┆ delta_mbp ┆ … ┆ dbp50     ┆ dbp90     ┆ dbp_sd    ┆ delta_db │
│ ---       ┆ 90_lag6   ┆ 90_lag12  ┆ _sd_lag1  ┆   ┆ ---       ┆ ---       ┆ ---       ┆ p10_lag1 │
│ str       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ ---      │
│           ┆ f64       ┆ f64       ┆ f64       ┆   ┆           ┆           ┆           ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ count     ┆ 3.262765e ┆ 3.087131e ┆ 3.204483e ┆ … ┆ 4.514509e ┆ 4.514509e ┆ 3.564411e ┆ 3.401078 │
│           ┆ 6         ┆ 6         ┆ 6         ┆   ┆ 6         ┆ 6         ┆ 6         ┆ e6       │
│ null_coun ┆ 1.636991e ┆ 1.812625e ┆ 1.695273e ┆ … ┆ 385247.0  ┆ 385247.0  ┆ 1.335345e ┆ 1.498678 │
│ t         ┆ 6         ┆ 6         ┆ 6         ┆   ┆           ┆           ┆ 6         ┆ e6       │
│ mean      ┆ -0.088165 ┆ 0.071155  ┆ -0.040199 ┆ … ┆ 62.611855 ┆ 67.546517 ┆ 5.953205  ┆ -0.03658 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 1        │
│ std       ┆ 18.056392 ┆ 19.578339 ┆ 7.374616  ┆ … ┆ 16.171093 ┆ 19.256202 ┆ 7.890585  ┆ 7.844691 │
│ min       ┆ -256.0    ┆ -255.1    ┆ -184.9107 ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ -275.0   │
│           ┆           ┆           ┆ 42        ┆   ┆           ┆           ┆           ┆          │
│ 25%       ┆ -7.9      ┆ -9.0      ┆ -1.983399 ┆ … ┆ 52.0      ┆ 56.0      ┆ 2.23354   ┆ -2.4     │
│ 50%       ┆ 0.0       ┆ 0.1       ┆ -0.02447  ┆ … ┆ 61.0      ┆ 65.0      ┆ 3.68732   ┆ 0.0      │
│ 75%       ┆ 8.0       ┆ 9.2       ┆ 1.915209  ┆ … ┆ 72.0      ┆ 76.1      ┆ 6.363961  ┆ 2.6      │
│ max       ┆ 245.0     ┆ 245.6     ┆ 195.97986 ┆ … ┆ 300.0     ┆ 300.0     ┆ 205.76807 ┆ 271.4    │
│           ┆           ┆           ┆ 4         ┆   ┆           ┆           ┆ 3         ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [25]:
describe_df(df, 150, 160)

shape: (9, 11)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ statistic ┆ delta_dbp ┆ delta_dbp ┆ delta_dbp ┆ … ┆ delta_dbp ┆ delta_dbp ┆ delta_dbp ┆ delta_db │
│ ---       ┆ 10_lag6   ┆ 10_lag12  ┆ 50_lag1   ┆   ┆ 90_lag6   ┆ 90_lag12  ┆ _sd_lag1  ┆ p_sd_lag │
│ str       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ 6        │
│           ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ count     ┆ 3.262526e ┆ 3.086904e ┆ 3.401078e ┆ … ┆ 3.262526e ┆ 3.086904e ┆ 3.204092e ┆ 3.018121 │
│           ┆ 6         ┆ 6         ┆ 6         ┆   ┆ 6         ┆ 6         ┆ 6         ┆ e6       │
│ null_coun ┆ 1.63723e6 ┆ 1.812852e ┆ 1.498678e ┆ … ┆ 1.63723e6 ┆ 1.812852e ┆ 1.695664e ┆ 1.881635 │
│ t         ┆           ┆ 6         ┆ 6         ┆   ┆           ┆ 6         ┆ 6         ┆ e6       │
│ mean      ┆ 0.031435  ┆ 0.089989  ┆ -0.065705 ┆ … ┆ -0.065552 ┆ 0.038055  ┆ -0.029601 ┆ 0.002265 │
│ std       ┆ 10.969325 ┆ 12.105592 ┆ 8.995     ┆ … ┆ 18.006815 ┆ 19.209163 ┆ 7.437926  ┆ 8.267154 │
│ min       ┆ -292.2    ┆ -269.0    ┆ -278.0    ┆ … ┆ -263.0    ┆ -258.9    ┆ -196.3164 ┆ -202.424 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 42        ┆ 135      │
│ 25%       ┆ -5.0      ┆ -6.0      ┆ -2.5      ┆ … ┆ -6.1      ┆ -7.2      ┆ -1.610776 ┆ -1.82546 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 6        │
│ 50%       ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ … ┆ 0.0       ┆ 0.0       ┆ -0.01679  ┆ 0.0      │
│ 75%       ┆ 5.0       ┆ 6.0       ┆ 2.5       ┆ … ┆ 6.1       ┆ 7.6       ┆ 1.563583  ┆ 1.824768 │
│ max       ┆ 261.0     ┆ 258.4     ┆ 271.0     ┆ … ┆ 260.0     ┆ 260.0     ┆ 176.48606 ┆ 195.9469 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 7         ┆ 46       │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [26]:
describe_df(df, 160, 170)

shape: (9, 11)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ statistic ┆ delta_dbp ┆ spo2_10   ┆ spo2_50   ┆ … ┆ delta_spo ┆ delta_spo ┆ delta_spo ┆ delta_sp │
│ ---       ┆ _sd_lag12 ┆ ---       ┆ ---       ┆   ┆ 2_10_lag6 ┆ 2_10_lag1 ┆ 2_50_lag1 ┆ o2_50_la │
│ str       ┆ ---       ┆ f64       ┆ f64       ┆   ┆ ---       ┆ 2         ┆ ---       ┆ g6       │
│           ┆ f64       ┆           ┆           ┆   ┆ f64       ┆ ---       ┆ f64       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆ f64       ┆           ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ count     ┆ 2.834906e ┆ 4.72485e6 ┆ 4.72485e6 ┆ … ┆ 4.349068e ┆ 4.127708e ┆ 4.562282e ┆ 4.349068 │
│           ┆ 6         ┆           ┆           ┆   ┆ 6         ┆ 6         ┆ 6         ┆ e6       │
│ null_coun ┆ 2.06485e6 ┆ 174906.0  ┆ 174906.0  ┆ … ┆ 550688.0  ┆ 772048.0  ┆ 337474.0  ┆ 550688.0 │
│ t         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ mean      ┆ 0.05278   ┆ 96.067343 ┆ 97.338053 ┆ … ┆ -0.052597 ┆ -0.100307 ┆ -0.010029 ┆ -0.05487 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 2        │
│ std       ┆ 8.488185  ┆ 4.152595  ┆ 3.105221  ┆ … ┆ 3.768255  ┆ 4.03818   ┆ 1.809912  ┆ 2.524533 │
│ min       ┆ -203.3867 ┆ 0.0       ┆ 0.0       ┆ … ┆ -100.0    ┆ -100.0    ┆ -100.0    ┆ -100.0   │
│           ┆ 07        ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 25%       ┆ -1.93851  ┆ 95.0      ┆ 96.0      ┆ … ┆ -1.0      ┆ -1.1      ┆ 0.0       ┆ -1.0     │
│ 50%       ┆ 0.027509  ┆ 97.0      ┆ 98.0      ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0      │
│ 75%       ┆ 1.995632  ┆ 98.9      ┆ 99.0      ┆ … ┆ 1.0       ┆ 1.0       ┆ 0.0       ┆ 1.0      │
│ max       ┆ 191.57014 ┆ 100.0     ┆ 100.0     ┆ … ┆ 100.0     ┆ 100.0     ┆ 100.0     ┆ 100.0    │
│           ┆ 3         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [27]:
describe_df(df, 170, 180)

shape: (9, 11)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ statistic ┆ delta_spo ┆ delta_spo ┆ delta_spo ┆ … ┆ delta_spo ┆ bp_invasi ┆ wbc       ┆ hemoglob │
│ ---       ┆ 2_50_lag1 ┆ 2_90_lag1 ┆ 2_90_lag6 ┆   ┆ 2_sd_lag1 ┆ ve        ┆ ---       ┆ in       │
│ str       ┆ 2         ┆ ---       ┆ ---       ┆   ┆ 2         ┆ ---       ┆ f64       ┆ ---      │
│           ┆ ---       ┆ f64       ┆ f64       ┆   ┆ ---       ┆ f64       ┆           ┆ f64      │
│           ┆ f64       ┆           ┆           ┆   ┆ f64       ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ count     ┆ 4.127708e ┆ 4.562282e ┆ 4.349068e ┆ … ┆ 4.066808e ┆ 4.81265e6 ┆ 4.00208e6 ┆ 3.990096 │
│           ┆ 6         ┆ 6         ┆ 6         ┆   ┆ 6         ┆           ┆           ┆ e6       │
│ null_coun ┆ 772048.0  ┆ 337474.0  ┆ 550688.0  ┆ … ┆ 832948.0  ┆ 87106.0   ┆ 897676.0  ┆ 909660.0 │
│ t         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ mean      ┆ -0.090109 ┆ -0.011025 ┆ -0.046626 ┆ … ┆ 0.012067  ┆ 0.671283  ┆ 10.818384 ┆ 10.25497 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 8        │
│ std       ┆ 2.763758  ┆ 1.459746  ┆ 2.039126  ┆ … ┆ 1.612181  ┆ 0.469747  ┆ 7.189804  ┆ 2.096217 │
│ min       ┆ -100.0    ┆ -100.0    ┆ -100.0    ┆ … ┆ -62.95996 ┆ 0.0       ┆ 0.0       ┆ -0.48    │
│           ┆           ┆           ┆           ┆   ┆ 7         ┆           ┆           ┆          │
│ 25%       ┆ -1.0      ┆ 0.0       ┆ -1.0      ┆ … ┆ -0.377214 ┆ 0.0       ┆ 6.91      ┆ 8.7      │
│ 50%       ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ … ┆ 0.0       ┆ 1.0       ┆ 9.56      ┆ 10.0     │
│ 75%       ┆ 1.0       ┆ 0.0       ┆ 1.0       ┆ … ┆ 0.421741  ┆ 1.0       ┆ 13.1      ┆ 11.5     │
│ max       ┆ 100.0     ┆ 100.0     ┆ 100.0     ┆ … ┆ 69.865118 ┆ 1.0       ┆ 636.5     ┆ 22.6     │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [28]:
describe_df(df, 180, 190)

shape: (9, 11)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ statistic ┆ platelet  ┆ sodium    ┆ creatinin ┆ … ┆ alanine_a ┆ total_bil ┆ crp       ┆ albumin  │
│ ---       ┆ ---       ┆ ---       ┆ e         ┆   ┆ minotrans ┆ irubin    ┆ ---       ┆ ---      │
│ str       ┆ f64       ┆ f64       ┆ ---       ┆   ┆ ferase    ┆ ---       ┆ f64       ┆ f64      │
│           ┆           ┆           ┆ f64       ┆   ┆ ---       ┆ f64       ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ f64       ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ count     ┆ 4.000982e ┆ 3.999708e ┆ 3.99035e6 ┆ … ┆ 3.939553e ┆ 3.910161e ┆ 3.762644e ┆ 3.685242 │
│           ┆ 6         ┆ 6         ┆           ┆   ┆ 6         ┆ 6         ┆ 6         ┆ e6       │
│ null_coun ┆ 898774.0  ┆ 900048.0  ┆ 909406.0  ┆ … ┆ 960203.0  ┆ 989595.0  ┆ 1.137112e ┆ 1.214514 │
│ t         ┆           ┆           ┆           ┆   ┆           ┆           ┆ 6         ┆ e6       │
│ mean      ┆ 193.92419 ┆ 140.17307 ┆ 1.437072  ┆ … ┆ 75.324478 ┆ 1.448995  ┆ 8.47933   ┆ 2.501873 │
│           ┆ 4         ┆ 3         ┆           ┆   ┆           ┆           ┆           ┆          │
│ std       ┆ 126.11493 ┆ 5.950658  ┆ 1.632597  ┆ … ┆ 257.88309 ┆ 3.111458  ┆ 8.379983  ┆ 0.684232 │
│           ┆ 9         ┆           ┆           ┆   ┆ 1         ┆           ┆           ┆          │
│ min       ┆ 0.0       ┆ 48.0      ┆ 0.01      ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.1      │
│ 25%       ┆ 105.0     ┆ 137.0     ┆ 0.6       ┆ … ┆ 15.0      ┆ 0.45      ┆ 1.969     ┆ 2.0      │
│ 50%       ┆ 173.0     ┆ 140.0     ┆ 0.84      ┆ … ┆ 27.0      ┆ 0.7       ┆ 5.858     ┆ 2.4      │
│ 75%       ┆ 254.0     ┆ 143.0     ┆ 1.5       ┆ … ┆ 56.0      ┆ 1.2       ┆ 12.61     ┆ 2.9      │
│ max       ┆ 1927.0    ┆ 198.0     ┆ 37.97     ┆ … ┆ 11202.0   ┆ 134.7     ┆ 76.6      ┆ 6.2      │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [29]:
describe_df(df, 190, 200)

shape: (9, 11)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ statistic ┆ rass_scor ┆ respirati ┆ coagulati ┆ … ┆ renal_24h ┆ sofa_24ho ┆ input_amo ┆ cumsum_i │
│ ---       ┆ e         ┆ on_24hour ┆ on_24hour ┆   ┆ ours      ┆ urs       ┆ unt       ┆ n        │
│ str       ┆ ---       ┆ s         ┆ s         ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│           ┆ f64       ┆ ---       ┆ ---       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
│           ┆           ┆ f64       ┆ f64       ┆   ┆           ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ count     ┆ 4.397116e ┆ 4.488377e ┆ 4.02413e6 ┆ … ┆ 4.179444e ┆ 4.899756e ┆ 4.899756e ┆ 4.899756 │
│           ┆ 6         ┆ 6         ┆           ┆   ┆ 6         ┆ 6         ┆ 6         ┆ e6       │
│ null_coun ┆ 502640.0  ┆ 411379.0  ┆ 875626.0  ┆ … ┆ 720312.0  ┆ 0.0       ┆ 0.0       ┆ 0.0      │
│ t         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ mean      ┆ -1.758012 ┆ 1.578014  ┆ 0.762408  ┆ … ┆ 1.159061  ┆ 6.2686    ┆ 106.62284 ┆ 29637.09 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 3         ┆ 9879     │
│ std       ┆ 1.982199  ┆ 1.087374  ┆ 1.072359  ┆ … ┆ 1.578254  ┆ 4.099557  ┆ 278.23750 ┆ 203432.9 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 5         ┆ 90625    │
│ min       ┆ -5.0      ┆ 0.0       ┆ 0.0       ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0      │
│ 25%       ┆ -4.0      ┆ 1.0       ┆ 0.0       ┆ … ┆ 0.0       ┆ 3.0       ┆ 20.0      ┆ 3521.333 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 333      │
│ 50%       ┆ -1.0      ┆ 2.0       ┆ 0.0       ┆ … ┆ 0.0       ┆ 6.0       ┆ 60.0      ┆ 10059.63 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 3333     │
│ 75%       ┆ 0.0       ┆ 2.0       ┆ 1.0       ┆ … ┆ 3.0       ┆ 9.0       ┆ 112.3     ┆ 25312.09 │
│ max       ┆ 4.0       ┆ 4.0       ┆ 4.0       ┆ … ┆ 4.0       ┆ 24.0      ┆ 100032.0  ┆ 8.5919e6 │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [30]:
describe_df(df, 200, 210)

shape: (9, 11)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ statistic ┆ window_to ┆ cumsum_ou ┆ cumsum_ba ┆ … ┆ active_in ┆ active_in ┆ active_in ┆ active_i │
│ ---       ┆ tal_outpu ┆ t         ┆ lance     ┆   ┆ gredient_ ┆ gredient_ ┆ gredient_ ┆ ngredien │
│ str       ┆ t         ┆ ---       ┆ ---       ┆   ┆ dexmedeto ┆ dopamine  ┆ midazolam ┆ t_dobuta │
│           ┆ ---       ┆ f64       ┆ f64       ┆   ┆ mid…      ┆ ---       ┆ ---       ┆ mine     │
│           ┆ f64       ┆           ┆           ┆   ┆ ---       ┆ f64       ┆ f64       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆ f64       ┆           ┆           ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ count     ┆ 4.899756e ┆ 4.899756e ┆ 4.899756e ┆ … ┆ 4.899756e ┆ 4.899756e ┆ 4.899756e ┆ 4.899756 │
│           ┆ 6         ┆ 6         ┆ 6         ┆   ┆ 6         ┆ 6         ┆ 6         ┆ e6       │
│ null_coun ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0      │
│ t         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ mean      ┆ 69.970926 ┆ 15894.007 ┆ 13743.092 ┆ … ┆ 0.015687  ┆ 0.561606  ┆ 0.555039  ┆ 0.749414 │
│           ┆           ┆ 728       ┆ 151       ┆   ┆           ┆           ┆           ┆          │
│ std       ┆ 95.259701 ┆ 28489.143 ┆ 188600.97 ┆ … ┆ 0.094112  ┆ 3.394437  ┆ 2.351753  ┆ 3.394129 │
│           ┆           ┆ 056       ┆ 9066      ┆   ┆           ┆           ┆           ┆          │
│ min       ┆ 0.0       ┆ 0.0       ┆ -428443.5 ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0      │
│           ┆           ┆           ┆ 40333     ┆   ┆           ┆           ┆           ┆          │
│ 25%       ┆ 24.48     ┆ 1957.917  ┆ -206.666  ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0      │
│ 50%       ┆ 50.583    ┆ 6690.005  ┆ 2029.086  ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0      │
│ 75%       ┆ 91.25     ┆ 18560.869 ┆ 7795.1352 ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0      │
│           ┆           ┆           ┆ 73        ┆   ┆           ┆           ┆           ┆          │
│ max       ┆ 28280.64  ┆ 541423.11 ┆ 8.0505e6  ┆ … ┆ 5.0       ┆ 383.5     ┆ 80.958333 ┆ 163.1839 │
│           ┆           ┆ 6         ┆           ┆   ┆           ┆           ┆           ┆ 29       │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [31]:
describe_df(df, 210, 222)

shape: (9, 12)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ statistic ┆ active_in ┆ active_in ┆ active_in ┆ … ┆ transfusi ┆ transfusi ┆ transfusi ┆ transfus │
│ ---       ┆ gredient_ ┆ gredient_ ┆ gredient_ ┆   ┆ on_rbc    ┆ on_platel ┆ on_plasma ┆ ion_albu │
│ str       ┆ landiolol ┆ vasopress ┆ remifenta ┆   ┆ ---       ┆ et        ┆ ---       ┆ min      │
│           ┆ ---       ┆ in        ┆ nil       ┆   ┆ f64       ┆ ---       ┆ f64       ┆ ---      │
│           ┆ f64       ┆ ---       ┆ ---       ┆   ┆           ┆ f64       ┆           ┆ f64      │
│           ┆           ┆ f64       ┆ f64       ┆   ┆           ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ count     ┆ 4.899756e ┆ 4.899756e ┆ 4.899756e ┆ … ┆ 4.899756e ┆ 4.899756e ┆ 4.899756e ┆ 4.899756 │
│           ┆ 6         ┆ 6         ┆ 6         ┆   ┆ 6         ┆ 6         ┆ 6         ┆ e6       │
│ null_coun ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0      │
│ t         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ mean      ┆ 0.226204  ┆ 0.032604  ┆ 0.001091  ┆ … ┆ 2.106507  ┆ 0.386908  ┆ 1.330155  ┆ 0.980675 │
│ std       ┆ 1.729248  ┆ 0.257309  ┆ 0.011609  ┆ … ┆ 23.475368 ┆ 8.570139  ┆ 23.409596 ┆ 12.25906 │
│ min       ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0      │
│ 25%       ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0      │
│ 50%       ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0      │
│ 75%       ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0      │
│ max       ┆ 75.0      ┆ 31.372549 ┆ 0.75      ┆ … ┆ 7361.7506 ┆ 2828.5713 ┆ 5091.4285 ┆ 4250.0   │
│           ┆           ┆           ┆           ┆   ┆           ┆ 84        ┆ 85        ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

## Cohort Splilt

In [32]:
# 全施設を8:2にsplitする方針
df_development = df.filter(pl.col('hospital_id').is_in([1, 2, 3, 5, 6, 7, 8, 9, 10, 11]))
del df # メモリ節約

In [33]:
# record数と症例数を確認
print('Number of records (model development cohort):', len(df_development))
print('Number of icu_stay_id (model development cohort):', len(df_development['icu_stay_id'].unique()))
print('Average number of records per icu_stay_id (model development cohort):', len(df_development) / len(df_development['icu_stay_id'].unique()))

Number of records (model development cohort): 4899756
Number of icu_stay_id (model development cohort): 41300
Average number of records per icu_stay_id (model development cohort): 118.6381598062954

In [34]:
df_development.write_csv(os.path.join(data_dir, df_development_file_name))